### PR TITLE
Fix data uncompression at NimbleEmojiIndex constructor

### PR DESCRIPTION
**Pull request by ekvedaras**
`uncompress` function does not return anything. It manipulates `data` object instead. Therefore, after uncompression `data` becames `undefined` and index is empty

### CODE REVIEW

**Comment by serebrov** [comment]
Note that besides the NimbleEmojiIndex constructor, the `uncompress` is also called here - https://github.com/jm-david/emoji-mart-vue/blob/master/src/components/picker/nimblePicker.vue#L140

**Comment by ekvedaras** [comment]
Updated remaining usages I've found of `uncompress`

**Comment by darivs** [comment]
please merge

**Comment by deen13** [comment]
plleeeaaaaasssseee

**Comment by deen13** [comment]
I'd like some merge

**Comment by ekvedaras** [comment]
This clearly dead and no longer relevant :)

**Pull request closed without merging**
